### ISSUE TITLE
Finish backend setup

### ISSUE THREAD

**Issue by Trafitto** [Trafitto/pioniere#1]
I've just created the project with `express-generator`.
You need to finish the setup and create the first endpoint.

The response must contain the video url and the view number, **fake data is fine at the moment**

**Comment by capitanfindusfi** [comment]
@Trafitto I'm working on this

**Comment by yesabhishek** [comment]
I am really invested in the idea in which you are working. Looking forward to understand the code. Maybe I will start by documenting it. Since I am new to Pug, please guide me.

**Comment by capitanfindusfi** [comment]
@Trafitto basically this issue can be closed with #5 which you have already merged
